export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const WIND_SENSOR_DATA_LOADING = 'WIND_SENSOR_DATA_LOADING';
export const WIND_SENSOR_DATA_SUCCESS = 'WIND_SENSOR_DATA_SUCCESS';
export const WIND_SENSOR_DATA_FAILURE = 'WIND_SENSOR_DATA_FAILURE';
export const WIND_SENSOR_STATUS_UPDATE = 'WIND_SENSOR_STATUS_UPDATE';
export const WIND_SENSOR_STATUS_LOADING = 'WIND_SENSOR_STATUS_LOADING';
export const FILTER_DATA_LOADING = 'FILTER_DATA_LOADING';

export const apiURL = 'http://localhost:8080';
