export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const REQUEST_RECENT_TRACKS = 'REQUEST_RECENT_TRACKS';
export const FAIL_RECENT_TRACKS = 'FAIL_RECENT_TRACKS';
export const GOT_RECENT_TRACKS = 'GOT_RECENT_TRACKS';

export const REQUEST_WATERCONSUMPTION_EVENTS =
  'REQUEST_WATERCONSUMPTION_EVENTS';
export const FAIL_WATERCONSUMPTION_EVENTS = 'FAIL_WATERCONSUMPTION_EVENTS';
export const GOT_WATERCONSUMPTION_EVENTS = 'GOT_WATERCONSUMPTION_EVENTS';
export const UPDATE_WATERCONSUMPTION_STATUS = 'UPDATE_WATERCONSUMPTION_STATUS';
export const LOADING_WATERCONSUMPTION_STATUS =
  'LOADING_WATERCONSUMPTION_STATUS';
export const LOADING_FILTER_DATA = 'LOADING_FILTER_DATA';
export const WATER_QUALITY_REQUEST_EVENTS = 'WATER_QUALITY_REQUEST_EVENTS';
export const WATER_QUALITY_SUCCESS_EVENTS = 'WATER_QUALITY_SUCCESS_EVENTS';
export const WATER_QUALITY_FAIL_EVENTS = 'WATER_QUALITY_FAIL_EVENTS';

export const WATER_QUALITY_SUCCESS_STATUS = 'WATER_QUALITY_REQUEST_STATUS';
export const WATER_QUALITY_FAIL_STATUS = 'WATER_QUALITY_REQUEST_STATUS';

export const WATER_QUALITY_SUCCESS_INFO = 'WATER_QUALITY_SUCCESS_INFO';
export const WATER_QUALITY_SUCCESS_STRUCTURE =
  'WATER_QUALITY_SUCCESS_STRUCTURE';
export const WATER_QUALITY_SUCCESS_CURRENT = 'WATER_QUALITY_SUCCESS_CURRENT';

export const WATER_QUALITY_FILTER = 'WATER_QUALITY_FILTER';

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const CARBON_MONOXIDE_SENSOR_DATA_LOADING =
  'CARBON_MONOXIDE_SENSOR_DATA_LOADING';
export const CARBON_MONOXIDE_SENSOR_DATA_SUCCESS =
  'CARBON_MONOXIDE_SENSOR_DATA_SUCCESS';
export const CARBON_MONOXIDE_SENSOR_DATA_FAILURE =
  'CARBON_MONOXIDE_SENSOR_DATA_FAILURE';
export const CARBON_MONOXIDE_SENSOR_STATUS_UPDATE =
  'CARBON_MONOXIDE_SENSOR_STATUS_UPDATE';
export const CARBON_MONOXIDE_SENSOR_STATUS_LOADING =
  'CARBON_MONOXIDE_SENSOR_STATUS_LOADING';
export const FILTER_DATA_LOADING = 'FILTER_DATA_LOADING';
export const WIND_SENSOR_DATA_LOADING = 'WIND_SENSOR_DATA_LOADING';
export const WIND_SENSOR_DATA_SUCCESS = 'WIND_SENSOR_DATA_SUCCESS';
export const WIND_SENSOR_DATA_FAILURE = 'WIND_SENSOR_DATA_FAILURE';
export const WIND_SENSOR_STATUS_UPDATE = 'WIND_SENSOR_STATUS_UPDATE';
export const WIND_SENSOR_STATUS_LOADING = 'WIND_SENSOR_STATUS_LOADING';

export const apiURL = 'http://localhost:8080';
