export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const WIND_SENSOR_DATA_LOADING = 'WIND_SENSOR_DATA_LOADING';
export const WIND_SENSOR_DATA_SUCCESS = 'WIND_SENSOR_DATA_SUCCESS';
export const WIND_SENSOR_DATA_FAILURE = 'WIND_SENSOR_DATA_FAILURE';
